services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\WechatOfficialAccountOAuth2Bundle\Command\:
    resource: '../../Command/'
  Tourze\WechatOfficialAccountOAuth2Bundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\WechatOfficialAccountOAuth2Bundle\Repository\:
    resource: '../../Repository/'
  Tourze\WechatOfficialAccountOAuth2Bundle\Service\:
    resource: '../../Service/'

  # EasyAdmin Controllers
  Tourze\WechatOfficialAccountOAuth2Bundle\Controller\Admin\:
    resource: '../../Controller/Admin/'
    tags: ['controller.service_arguments']

  # Menu Provider
  Tourze\WechatOfficialAccountOAuth2Bundle\Menu\WechatOAuth2MenuProvider:
    tags: ['easy-admin-menu.provider']
  
  # Admin Menu
  Tourze\WechatOfficialAccountOAuth2Bundle\Service\AdminMenu:
    tags: ['easy-admin-menu.provider']

  # OAuth2 Controllers
  Tourze\WechatOfficialAccountOAuth2Bundle\Controller\WechatOAuth2AuthorizeController:
    tags: ['controller.service_arguments']

  Tourze\WechatOfficialAccountOAuth2Bundle\Controller\WechatOAuth2CallbackController:
    tags: ['controller.service_arguments']
