services:
  # DataFixtures 服务仅在测试环境中可用
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\WechatOfficialAccountOAuth2Bundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']